# prefix C-<<space>>
unbind C-b
set -g prefix C-Space
bind C-Space send-prefix

# TPM
set -g @plugin 'tmux-plugins/tpm'

# tmux-ssh
set -g @plugin 'cdpb/tmux-ssh'

# deine Shell
set -g default-command "/bin/zsh -l"

# TPM loader (muss am Ende stehen)
run '~/.tmux/plugins/tpm/tpm'
